### ISSUE TITLE
UTC option does not exist on Sheet2JSONOpts - but it exists upstream

### ISSUE THREAD

**Issue by alexanderisacson** [redoper1/xlsx-js-style#2]
The interface `export interface Sheet2JSONOpts extends DateNFOption` does not have the property `UTC` which exits upstream. 

See: https://docs.sheetjs.com/docs/csf/features/dates#utc-option

Strange that it has gone missing since `xlsx-js-style` should be based on the latest version of `sheetjs`.

**Comment by redoper1** [comment]
Hello @alexanderisacson,

yeah that's very strange. I will investigate it as soon as possible.

**Comment by redoper1** [comment]
It appears that I fogot to commit updated types from the upstream. I will fix it as soon as possible and release a new version.

**Comment by redoper1** [comment]
Hello @alexanderisacson,

I just realeased a new version with updated types, so this issue should be fixed.

**Comment by alexanderisacson** [comment]
Great!

I can confirm that it works!

Thanks
/Alexander
